// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLatestResolution(arg1:main.WindowSize):Promise<void>;

export function AddNote(arg1:string):Promise<Array<main.Note>>;

export function GetLatestResolution():Promise<main.WindowSize>;

export function GetNotes():Promise<Array<main.Note>>;

export function ListenForResize():Promise<void>;

export function OnWindowResized(arg1:number,arg2:number):Promise<void>;

export function RemoveNote(arg1:number):Promise<Array<main.Note>>;

export function SetAppResolution(arg1:main.WindowSize):Promise<void>;

export function ToggleLock(arg1:number):Promise<Array<main.Note>>;

export function UpdateNote(arg1:number,arg2:string):Promise<Array<main.Note>>;
