// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddNote(arg1:string):Promise<Array<main.Note>>;

export function GetNotes():Promise<Array<main.Note>>;

export function RemoveNote(arg1:number):Promise<Array<main.Note>>;

export function UpdateNote(arg1:number,arg2:string):Promise<Array<main.Note>>;
