// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLatestResolution(arg1) {
  return window['go']['main']['App']['AddLatestResolution'](arg1);
}

export function AddNote(arg1) {
  return window['go']['main']['App']['AddNote'](arg1);
}

export function GetLatestResolution() {
  return window['go']['main']['App']['GetLatestResolution']();
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function ListenForResize() {
  return window['go']['main']['App']['ListenForResize']();
}

export function OnWindowResized(arg1, arg2) {
  return window['go']['main']['App']['OnWindowResized'](arg1, arg2);
}

export function RemoveNote(arg1) {
  return window['go']['main']['App']['RemoveNote'](arg1);
}

export function SetAppResolution(arg1) {
  return window['go']['main']['App']['SetAppResolution'](arg1);
}

export function ToggleLock(arg1) {
  return window['go']['main']['App']['ToggleLock'](arg1);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}
